@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Sep 09 14:08:37 +0200 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim sim_pi_behav -key {Behavioral:sim_1:Functional:sim_pi} -tclbatch sim_pi.tcl -protoinst "protoinst_files/test_driver_pwm.protoinst" -protoinst "protoinst_files/test_mesure_vitesse.protoinst" -view C:/Users/Thomas/Desktop/TP_MISTRE/TP_ROBOTIQUE/test_sur_7010_fpga/sim_decodeur_behav.wcfg -log simulate.log"
call xsim  sim_pi_behav -key {Behavioral:sim_1:Functional:sim_pi} -tclbatch sim_pi.tcl -protoinst "protoinst_files/test_driver_pwm.protoinst" -protoinst "protoinst_files/test_mesure_vitesse.protoinst" -view C:/Users/Thomas/Desktop/TP_MISTRE/TP_ROBOTIQUE/test_sur_7010_fpga/sim_decodeur_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
