# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Zybo/Zybo-Z7-Master.xdc

# IP: ip/dsp_mult16/dsp_mult16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_mult16 || ORIG_REF_NAME==dsp_mult16} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIR5_Mult_0_0/design_1_FIR5_Mult_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FIR5_Mult_0_0 || ORIG_REF_NAME==design_1_FIR5_Mult_0_0} -quiet] -quiet

# IP: ip/dsp_mult16/dsp_mult16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_mult16 || ORIG_REF_NAME==dsp_mult16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_signals_gen_0_0/design_1_signals_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_signals_gen_0_0 || ORIG_REF_NAME==design_1_signals_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIR5_Add_0_0/design_1_FIR5_Add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FIR5_Add_0_0 || ORIG_REF_NAME==design_1_FIR5_Add_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_1/design_1_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_1 || ORIG_REF_NAME==design_1_system_ila_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/Thomas/Desktop/TP_MISTRE/TP_FPGA/TP2/FIR5_Timings_ILA/FIR5_Timings_ILA/FIR5_Timings_ILA.gen/sources_1/bd/design_1/design_1_ooc.xdc
