# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Thomas/Desktop/TP_MISTRE/TP_FPGA/TP2/FIR5_Timings_ILA/FIR5_Timings_ILA/FIR5_Timings_ILA.srcs/sources_1/bd/design_1/ip/design_1_FIR5_Mult_0_0/design_1_FIR5_Mult_0_0.xci
# IP: The module: 'design_1_FIR5_Mult_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Thomas/Desktop/TP_MISTRE/TP_FPGA/TP2/FIR5_Timings_ILA/FIR5_Timings_ILA/FIR5_Timings_ILA.srcs/sources_1/ip/dsp_mult16/dsp_mult16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_mult16 || ORIG_REF_NAME==dsp_mult16} -quiet] -quiet

# XDC: c:/Users/Thomas/Desktop/TP_MISTRE/TP_FPGA/TP2/FIR5_Timings_ILA/FIR5_Timings_ILA/FIR5_Timings_ILA.gen/sources_1/bd/design_1/ip/design_1_FIR5_Mult_0_0/design_1_FIR5_Mult_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FIR5_Mult_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Thomas/Desktop/TP_MISTRE/TP_FPGA/TP2/FIR5_Timings_ILA/FIR5_Timings_ILA/FIR5_Timings_ILA.srcs/sources_1/bd/design_1/ip/design_1_FIR5_Mult_0_0/design_1_FIR5_Mult_0_0.xci
# IP: The module: 'design_1_FIR5_Mult_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Thomas/Desktop/TP_MISTRE/TP_FPGA/TP2/FIR5_Timings_ILA/FIR5_Timings_ILA/FIR5_Timings_ILA.srcs/sources_1/ip/dsp_mult16/dsp_mult16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_mult16 || ORIG_REF_NAME==dsp_mult16} -quiet] -quiet

# XDC: c:/Users/Thomas/Desktop/TP_MISTRE/TP_FPGA/TP2/FIR5_Timings_ILA/FIR5_Timings_ILA/FIR5_Timings_ILA.gen/sources_1/bd/design_1/ip/design_1_FIR5_Mult_0_0/design_1_FIR5_Mult_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FIR5_Mult_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
