webtalk_init -webtalk_dir C:/Users/Thomas/Desktop/TP MISTRE/TP_FPGA/FIR5/FIR5.sim/sim_1/behav/xsim/xsim.dir/FIR_DAC_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 16 07:33:24 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cb86b4f3-b44f-4b21-b3fc-765976c9b176" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d778a7d63f2b40d081f62021906e452a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-14700KF" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3418 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "20 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10024_KB" -context "xsim\\usage"
webtalk_transmit -clientid 695803938 -regid "" -xml C:/Users/Thomas/Desktop/TP MISTRE/TP_FPGA/FIR5/FIR5.sim/sim_1/behav/xsim/xsim.dir/FIR_DAC_top_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Thomas/Desktop/TP MISTRE/TP_FPGA/FIR5/FIR5.sim/sim_1/behav/xsim/xsim.dir/FIR_DAC_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Thomas/Desktop/TP MISTRE/TP_FPGA/FIR5/FIR5.sim/sim_1/behav/xsim/xsim.dir/FIR_DAC_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
